### ISSUE TITLE
Feature Request: Hide tags with no values / Hide tags in general / Sort tags

### ISSUE THREAD

**Issue by IronTooch** [rmountjoy92/DashMachine#42] opened 2020-03-19 13:13 UTC
Hello! So it looks like the current implementation shows tags that have no actual applications if it's invisible from the logged in user, and it seems like it would make sense to hide them entirely if there are no records. 

Similarly, it would be cool if you could temporarily hide an application with a settings change, similar to "hidden = true". 

Finally, for usability's sake for other people, being able to order/sort tags would be super cool. 

Thanks!

**Comment by rmountjoy92** [comment] 2020-03-19 13:21
thanks! this is a duplicate of #28

**Closed by rmountjoy92** 2020-03-19 13:21 UTC
